trigger:
- master
- richnav-test
pr: none

jobs:
- job: RichCodeNav_Indexing
  pool:
    name: Hosted Windows 2019 with VS2019
  variables:
    EnableRichCodeNavigation: true
  timeoutInMinutes: 200

  steps:
    - task: PowerShell@2
      displayName: Build
      inputs:
        filePath: eng/build.ps1
        arguments: -ci -restore -build -binaryLog -configuration Debug -prepareMachine

    - task: CopyFiles@2
      inputs:
        Contents: $(Build.SourcesDirectory)/artifacts/bin/**/*.RichCodeNav.log
        TargetFolder: $(Build.ArtifactStagingDirectory)
      displayName: Copy RichNav log to Build Artifacts

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: Artifacts
      displayName: "Publish Build Artifacts"

    - task: RichCodeNavIndexer@0
      displayName: RichCodeNav Upload
      inputs:
        languages: 'csharp'
        githubServiceConnection: 'xuachen'
        nugetFeed: 'https://devdiv.pkgs.visualstudio.com/Personal/_packaging/richnav/nuget/v3/index.json'
        isPrivateFeed: true
        nugetVersion: '0.1.1856-alpha'
        environment: development
        richNavLogOutputDirectory: $(Build.SourcesDirectory)/artifacts/bin
      continueOnError: true

      env:
        DOTNET_ROOT: $(Build.SourcesDirectory)/.dotnet
