trigger:
- master
- richnav-test
pr: none

jobs:
- job: RichCodeNav_Indexing
  pool:
    name: DotNetCore-Build
  variables:
    EnableRichCodeNavigation: true
  timeoutInMinutes: 200

  steps:
    - task: PowerShell@2
      displayName: Build
      inputs:
        filePath: eng/build.ps1
        arguments: -ci -restore -build -binaryLog -configuration Debug -prepareMachine

    - task: RichCodeNavIndexer@0
      displayName: RichCodeNav Upload
      inputs:
        languages: 'csharp'
        githubServiceConnection: 'xuachen'
        nugetFeed: 'https://devdiv.pkgs.visualstudio.com/Personal/_packaging/richnav/nuget/v3/index.json'
        isPrivateFeed: true
        nugetVersion: '0.1.1856-alpha'
        environment: development
        richNavLogOutputDirectory: $(Build.SourcesDirectory)/artifacts/bin
      continueOnError: true

      env:
        DOTNET_ROOT: $(Build.SourcesDirectory)/.dotnet
